
language: objective-c
before_install:
  - brew update
  - brew upgrade xctool
  - gem install cocoapods -v '0.32.1'
  - pod repo add cloudspace https://github.com/cloudspace/Cloudspace-iOS-PodSpecs.git
script:
  #- xctool -workspace EasyReader.xcworkspace -scheme Development -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace EasyReader.xcworkspace -scheme Development -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO

